export const CERTIFICATE_TEMPLATES = [
  {
    id: "academic-certificate",
    name: "Academic Certificate",
    variables: [
      { name: "StudentName", value: "John Doe", placeholder: "Student Name" },
      { name: "CourseName", value: "Computer Science", placeholder: "Course Name" },
      { name: "DegreeDate", value: new Date().toLocaleDateString(), placeholder: "Degree Date" },
      { name: "SchoolName", value: "University of Excellence", placeholder: "School Name" },
    ],
    pages: [
      {
        id: "page1",
        name: "Certificate Page",
        background: "#ffffff",
        backgroundType: "color",
        size: "a4-landscape",
        elements: [
          {
            id: "title",
            type: "text",
            content: "Certificate of Completion",
            x: 561,
            y: 80,
            fontSize: 36,
            fontFamily: "serif",
            color: "#1a365d",
            fontWeight: "bold",
            textAlign: "center",
          },
          {
            id: "student-name",
            type: "text",
            content: "This is to certify that {{StudentName}}",
            x: 561,
            y: 200,
            fontSize: 24,
            fontFamily: "serif",
            color: "#2d3748",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "course",
            type: "text",
            content: "has successfully completed {{CourseName}}",
            x: 561,
            y: 260,
            fontSize: 20,
            fontFamily: "serif",
            color: "#2d3748",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "school",
            type: "text",
            content: "at {{SchoolName}}",
            x: 561,
            y: 320,
            fontSize: 18,
            fontFamily: "serif",
            color: "#4a5568",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "date",
            type: "text",
            content: "Date: {{DegreeDate}}",
            x: 561,
            y: 450,
            fontSize: 16,
            fontFamily: "serif",
            color: "#4a5568",
            fontWeight: "normal",
            textAlign: "center",
          },
        ],
      },
    ],
  },
  {
    id: "achievement-award",
    name: "Achievement Award",
    variables: [
      { name: "StudentName", value: "Jane Smith", placeholder: "Student Name" },
      { name: "Achievement", value: "Outstanding Performance", placeholder: "Achievement" },
      { name: "AwardDate", value: new Date().toLocaleDateString(), placeholder: "Award Date" },
      { name: "Organization", value: "Excellence Academy", placeholder: "Organization" },
    ],
    pages: [
      {
        id: "page1",
        name: "Award Page",
        background: "#f8f9fa",
        backgroundType: "color",
        size: "a4-landscape",
        elements: [
          {
            id: "award-title",
            type: "text",
            content: "CERTIFICATE OF ACHIEVEMENT",
            x: 561,
            y: 60,
            fontSize: 32,
            fontFamily: "sans-serif",
            color: "#d4af37",
            fontWeight: "bold",
            textAlign: "center",
          },
          {
            id: "presented-to",
            type: "text",
            content: "Presented to",
            x: 561,
            y: 150,
            fontSize: 18,
            fontFamily: "serif",
            color: "#666",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "recipient-name",
            type: "text",
            content: "{{StudentName}}",
            x: 561,
            y: 200,
            fontSize: 28,
            fontFamily: "cursive",
            color: "#2c3e50",
            fontWeight: "bold",
            textAlign: "center",
          },
          {
            id: "achievement-text",
            type: "text",
            content: "For {{Achievement}}",
            x: 561,
            y: 280,
            fontSize: 20,
            fontFamily: "serif",
            color: "#34495e",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "organization",
            type: "text",
            content: "{{Organization}}",
            x: 561,
            y: 380,
            fontSize: 18,
            fontFamily: "serif",
            color: "#7f8c8d",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "award-date",
            type: "text",
            content: "{{AwardDate}}",
            x: 561,
            y: 450,
            fontSize: 16,
            fontFamily: "serif",
            color: "#95a5a6",
            fontWeight: "normal",
            textAlign: "center",
          },
        ],
      },
    ],
  },
  // Add other templates here...
]
