export const PREDEFINED_VARIABLES = [
  { label: "Student Name", value: "{{StudentName}}" },
  { label: "Mother's Name", value: "{{motherName}}" },
  { label: "Father's Name", value: "{{fatherName}}" },
  { label: "Enrollment No", value: "{{EnrollmentNo}}" },
  { label: "Aadhaar No.", value: "{{AadhaarNo}}" },
  { label: "Religion", value: "{{Religion}}" },
  { label: "Caste", value: "{{Caste}}" },
  { label: "Transcript ID", value: "{{TranscriptID}}" },
  { label: "Obtained Marks", value: "{{ObtainedMarks}}" },
  { label: "Obtained Grades", value: "{{ObtainedGrades}}" },
  { label: "Total Marks", value: "{{TotalMarks}}" },
  { label: "SGPA", value: "{{SGPA}}" },
  { label: "CGPA", value: "{{CGPA}}" },
  { label: "Percentage", value: "{{Percentage}}" },
  { label: "EvaluatedBy", value: "{{EvaluatedBy}}" },
  { label: "ApprovedBy", value: "{{ApprovedBy}}" },
  { label: "Program Name", value: "{{ProgramName}}" },
  { label: "Program Duration", value: "{{programDuration}}" },
  { label: "Course Name", value: "{{CourseName}}" },
  { label: "Batch Name", value: "{{NewBatchName}}" },
  { label: "Batch Code", value: "{{BatchCode}}" },
  { label: "Batch Start Date", value: "{{BatchStartDate}}" },
  { label: "Batch End Date", value: "{{BatchEndDate}}" },
  { label: "Batch Duration", value: "{{BatchDuration}}" },
  { label: "Modules", value: "{{Modules}}" },
  { label: "Hall Admit Number", value: "{{HallAdmitNumber}}" },
  { label: "Serial No.", value: "{{serialNo}}" },
  { label: "Registration No.", value: "{{registrationNo}}" },
  { label: "Division", value: "{{Division}}" },
  { label: "DivisionInRegional", value: "{{DivisionInRegional}}" },
  { label: "Stream Name", value: "{{DepartmentName}}" },
  { label: "Stream Code", value: "{{DepartmentCode}}" },
  { label: "School Name", value: "{{SchoolName}}" },
  { label: "Student Name(Regional)", value: "{{regionalName}}" },
  { label: "Mother Name(Regional)", value: "{{regionalMotherName}}" },
  { label: "Father Name(Regional)", value: "{{regionalFatherName}}" },
  { label: "School Name(Regional)", value: "{{schoolRegionalName}}" },
  { label: "Stream Name(Regional)", value: "{{deptNameRegional}}" },
  { label: "Program Name(Regional)", value: "{{programNameInRegional}}" },
  { label: "Examination Centre", value: "{{ExamCentre}}" },
  { label: "State", value: "{{State}}" },
  { label: "District", value: "{{District}}" },
  { label: "Date of Birth", value: "{{DateOfBirth}}" },
  { label: "Exam Date", value: "{{ExamDate}}" },
  { label: "Exam Date (Regional)", value: "{{ExamDateRegional}}" },
  { label: "Degree Date", value: "{{DegreeDate}}" },
  { label: "Degree Date (Regional)", value: "{{DegreeDateRegional}}" },
  { label: "Academic Year", value: "{{AcademicYear}}" },
  { label: "Digilocker Id", value: "{{DigilockerId}}" },
  { label: "Certificate No", value: "{{certificateNo}}" },
  { label: "Total Credits", value: "{{TotalCredits}}" },
  { label: "Obtained Credits", value: "{{ObtainedCredits}}" },
  { label: "Credit Point", value: "{{CreditPoint}}" },
  { label: "Grade Point", value: "{{GradePoint}}" },
  { label: "Percentile", value: "{{Percentile}}" },
  { label: "Rank", value: "{{Rank}}" },
  { label: "Result", value: "{{Result}}" },
  { label: "Remarks", value: "{{Remarks}}" },
  { label: "Email", value: "{{Email}}" },
  { label: "Phone Number", value: "{{PhoneNumber}}" },
  { label: "Specialization", value: "{{Specialization}}" },
]
