import type { Template, PredefinedVariable } from "@/types/certificate"

export const PREDEFINED_VARIABLES: PredefinedVariable[] = [
  { label: "Student Name", value: "{{StudentName}}" },
  { label: "Mother's Name", value: "{{motherName}}" },
  { label: "Father's Name", value: "{{fatherName}}" },
  { label: "Enrollment No", value: "{{EnrollmentNo}}" },
  { label: "Aadhaar No.", value: "{{AadhaarNo}}" },
  { label: "Religion", value: "{{Religion}}" },
  { label: "Caste", value: "{{Caste}}" },
  { label: "Transcript ID", value: "{{TranscriptID}}" },
  { label: "Obtained Marks", value: "{{ObtainedMarks}}" },
  { label: "Obtained Grades", value: "{{ObtainedGrades}}" },
  { label: "Total Marks", value: "{{TotalMarks}}" },
  { label: "SGPA", value: "{{SGPA}}" },
  { label: "CGPA", value: "{{CGPA}}" },
  { label: "Percentage", value: "{{Percentage}}" },
  { label: "EvaluatedBy", value: "{{EvaluatedBy}}" },
  { label: "ApprovedBy", value: "{{ApprovedBy}}" },
  { label: "Program Name", value: "{{ProgramName}}" },
  { label: "Program Duration", value: "{{programDuration}}" },
  { label: "Course Name", value: "{{CourseName}}" },
  { label: "Batch Name", value: "{{NewBatchName}}" },
  { label: "Batch Code", value: "{{BatchCode}}" },
  { label: "Batch Start Date", value: "{{BatchStartDate}}" },
  { label: "Batch End Date", value: "{{BatchEndDate}}" },
  { label: "Batch Duration", value: "{{BatchDuration}}" },
  { label: "Modules", value: "{{Modules}}" },
  { label: "Hall Admit Number", value: "{{HallAdmitNumber}}" },
  { label: "Serial No.", value: "{{serialNo}}" },
  { label: "Registration No.", value: "{{registrationNo}}" },
  { label: "Division", value: "{{Division}}" },
  { label: "DivisionInRegional", value: "{{DivisionInRegional}}" },
  { label: "Stream Name", value: "{{DepartmentName}}" },
  { label: "Stream Code", value: "{{DepartmentCode}}" },
  { label: "School Name", value: "{{SchoolName}}" },
  { label: "Student Name(Regional)", value: "{{regionalName}}" },
  { label: "Mother Name(Regional)", value: "{{regionalMotherName}}" },
  { label: "Father Name(Regional)", value: "{{regionalFatherName}}" },
  { label: "School Name(Regional)", value: "{{schoolRegionalName}}" },
  { label: "Stream Name(Regional)", value: "{{deptNameRegional}}" },
  { label: "Program Name(Regional)", value: "{{programNameInRegional}}" },
  { label: "Examination Centre", value: "{{ExamCentre}}" },
  { label: "State", value: "{{State}}" },
  { label: "District", value: "{{District}}" },
  { label: "Date of Birth", value: "{{DateOfBirth}}" },
  { label: "Exam Date", value: "{{ExamDate}}" },
  { label: "Exam Date (Regional)", value: "{{ExamDateRegional}}" },
  { label: "Degree Date", value: "{{DegreeDate}}" },
  { label: "Degree Date (Regional)", value: "{{DegreeDateRegional}}" },
  { label: "Academic Year", value: "{{AcademicYear}}" },
  { label: "Digilocker Id", value: "{{DigilockerId}}" },
  { label: "Certificate No", value: "{{certificateNo}}" },
  { label: "Total Credits", value: "{{TotalCredits}}" },
  { label: "Obtained Credits", value: "{{ObtainedCredits}}" },
  { label: "Credit Point", value: "{{CreditPoint}}" },
  { label: "Grade Point", value: "{{GradePoint}}" },
  { label: "Percentile", value: "{{Percentile}}" },
  { label: "Rank", value: "{{Rank}}" },
  { label: "Result", value: "{{Result}}" },
  { label: "Remarks", value: "{{Remarks}}" },
  { label: "Email", value: "{{Email}}" },
  { label: "Phone Number", value: "{{PhoneNumber}}" },
  { label: "Specialization", value: "{{Specialization}}" },
]

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "academic-certificate",
    name: "Academic Certificate",
    variables: [
      { name: "StudentName", value: "John Doe", placeholder: "Student Name" },
      { name: "CourseName", value: "Computer Science", placeholder: "Course Name" },
      { name: "DegreeDate", value: new Date().toLocaleDateString(), placeholder: "Degree Date" },
      { name: "SchoolName", value: "University of Excellence", placeholder: "School Name" },
    ],
    pages: [
      {
        id: "page1",
        name: "Certificate Page",
        background: "#ffffff",
        backgroundType: "color",
        elements: [
          {
            id: "title",
            type: "text",
            content: "Certificate of Completion",
            x: 400,
            y: 80,
            fontSize: 36,
            fontFamily: "serif",
            color: "#1a365d",
            fontWeight: "bold",
            textAlign: "center",
          },
          {
            id: "student-name",
            type: "text",
            content: "This is to certify that {{StudentName}}",
            x: 400,
            y: 180,
            fontSize: 24,
            fontFamily: "serif",
            color: "#2d3748",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "course",
            type: "text",
            content: "has successfully completed {{CourseName}}",
            x: 400,
            y: 230,
            fontSize: 20,
            fontFamily: "serif",
            color: "#2d3748",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "school",
            type: "text",
            content: "at {{SchoolName}}",
            x: 400,
            y: 280,
            fontSize: 18,
            fontFamily: "serif",
            color: "#4a5568",
            fontWeight: "normal",
            textAlign: "center",
          },
          {
            id: "date",
            type: "text",
            content: "Date: {{DegreeDate}}",
            x: 400,
            y: 380,
            fontSize: 16,
            fontFamily: "serif",
            color: "#4a5568",
            fontWeight: "normal",
            textAlign: "center",
          },
        ],
      },
    ],
  },
]

export const FONT_FAMILIES = [
  { value: "serif", label: "Serif" },
  { value: "sans-serif", label: "Sans Serif" },
  { value: "monospace", label: "Monospace" },
  { value: "cursive", label: "Cursive" },
  { value: "fantasy", label: "Fantasy" },
]

export const FONT_WEIGHTS = [
  { value: "normal", label: "Normal" },
  { value: "bold", label: "Bold" },
  { value: "100", label: "Thin" },
  { value: "300", label: "Light" },
  { value: "500", label: "Medium" },
  { value: "700", label: "Bold" },
  { value: "900", label: "Black" },
]

export const TEXT_ALIGNMENTS = [
  { value: "left", label: "Left" },
  { value: "center", label: "Center" },
  { value: "right", label: "Right" },
]
